accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$', views.signup_view, name="signup"), # url de la page de création    mb#
    url(r'^login/$', views.login_view, name="login"),    # url de la page de connexion   mb#
    url(r'^logout/$', views.logout_view, name="logout"), # url de la déconnexion         mb#
]

articles/urls.py
from django.conf.urls import url
from . import views

app_name = 'articles'

urlpatterns = [
    url(r'^$', views.article_list, name="list"),                      # url de la liste d'articles    mb#
    url(r'^create/$', views.article_create, name="create"),           # url de la création d'article  mb#
    url(r'^(?P<slug>[\w-]+)/$', views.article_detail, name="detail"), # url d'un article avec le slug mb#
]

microlly/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^articles/', include('articles.urls')),           # url des articles   #
    url(r'^accounts/', include('accounts.urls')),           # url des connexions #
    url(r'^$', article_views.article_list, name="home"),    # url de l'accueil   #
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User

class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, default=None, on_delete=models.PROTECT)

    def __str__(self):
        return self.title

     # Affiche uniquement les 100 premiers caractères du contenu de l'article dans la preview mb#
    def snippet(self):
        return self.body[:100] + '...'

articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'body', 'slug', 'thumb',]

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Affiche la création de compte               mb#
def signup_view(request):
    if request.method == 'POST':
         form = UserCreationForm(request.POST)
         if form.is_valid():
             user = form.save()
             # Connecte l'utilisateur         mb#
             login(request, user)
             return redirect('articles:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', { 'form': form })

# Affiche la connexion                        mb#
def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # Connecte l'utilisateur          mb#
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
               return redirect('articles:list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', { 'form': form })

# Déconnecte et renvoie à la liste d'articles mb#
def logout_view(request):
    if request.method == 'POST':
            # Déconnecte l'utilisateur        mb#
            logout(request)
            return redirect('articles:list')

articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from django.contrib.auth.decorators import login_required
from . import forms

# Affiche la liste des articles    mb#
def article_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request, 'articles/article_list.html', { 'articles': articles })

# Affiche un article               mb#
def article_detail(request, slug):
    article = Article.objects.get(slug=slug)
    return render(request, 'articles/article_detail.html', { 'article': article })

# Affiche la création d'article    mb#
# L'utilisateur doit être connecté mb#
@login_required(login_url="/accounts/login/")
def article_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            # Enregistre l'article dans la bdd mb#
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()
    return render(request, 'articles/article_create.html', { 'form': form })

microlly/views.py
from django.shortcuts import render

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Se connecter :</h1>
    <form class="site-form" action="{% url 'accounts:login' %}" method="post">
        <!-- Permet d'empêcher les modifications hasardeuses mb-->
        {% csrf_token %}
        <!-- Inclut le formulaire de connexion               mb-->
        {{ form }}
        <!-- Vérifie que le formulaire est rempli            mb-->
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}" />
        {% endif %}
        <input type="submit" value="Se connecter" />
    </form>
    <p>Pas de compte ? <a href="{% url 'accounts:signup' %}">Inscrivez-vous !</a></p>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>S'inscrire :</h1>
    <form class="site-form" action="{% url 'accounts:signup' %}" method="post">
        <!-- Permet d'empêcher les modifications hasardeuses mb-->
        {% csrf_token %}
        <!-- Inclut le formulaire de connexion               mb-->
        {{ form }}
        <input type="submit" value="S'inscrire">
    </form>
{% endblock %}

articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="create-article">
        <h2>Créer un nouvel article :</h2>
        <form class="site-form" action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
            <!-- Permet d'empêcher les modifications hasardeuses mb-->
            {% csrf_token %}
            <!-- Inclut le formulaire de connexion               mb-->
            {{ form }}
            <input type="submit" value="Créer">
        </form>
    </div>
    <!-- Script pour passer le slug mb-->
    <script src="/static/slugify.js"></script>
{% endblock %}

articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="article-detail">
    <div class="article">
        <img src="{{ article.thumb.url }}" />
        <h2>{{ article.title }}</h2>
        <p>{{ article.body }}</p>
        <p>Créé par : {{ article.author.username }}</p>
        <p>{{ article.date }}</p>
    </div>
</div>
{% endblock %}

articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}

{% block content%}
    <h1>Microblog lunaire pour cowboys intergalactiques</h1>
    <div class="articles">
    <!-- Affiche les articles par date décroissante -->
    {% for article in articles reversed%}
        <div class="article">
            <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{ article.title }}</a></h2>
            <p>{{ article.snippet }}</p>
            <p>{{ article.date }}</p>
            <p class="author">Créé par : {{ article.author.username }}</p>
        </div>
    {% endfor %}
    </div>
{% endblock %}

templates/base_layout.html
<!-- Permet de gérer les fichiers statiques (images et css)             mb--> 
<!-- On les récupère depuis le dossier défini dans microlly/settings.py mb-->
{% load static from staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Microlly</title>
        <link rel="stylesheet" href="{% static 'styles.css' %}">
		<link rel="icon" href="{% static 'favicon.ico' %}">
    </head>
    <body>
        <header class="wrapper">
            <h1><a href="{% url 'home' %}"><img src="{% static 'coffee.png' %}" width="50" height="50" alt="logo">Microlly</a></h1>
            <nav>
                <ul>
                    <!-- Permet de vérifier si un utilisateur est connecté mb-->
                    {% if user.is_authenticated %}
                    <li>
                        <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                            <!-- Permet d'empêcher les modifications hasardeuses mb-->
                            {% csrf_token %}
                            <button type="submit">Se déconnecter</button>
                        </form>
                    </li>
                    <li><a href="{% url 'articles:create' %}" class="highlight">Nouvel article</a></li>
                    <!-- Si il n'y a pas d'utilisateur connecté mb-->
                    {% else %}
                    <li><a href="{% url 'accounts:login' %}">Se connecter</a></li>
                    <li><a href="{% url 'accounts:signup' %}">S'inscrire</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <div class="wrapper">
            <!-- Permet d'hériter d'un autre fichier html mb-->
            <!-- Avec extends                             mb-->
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>